### ISSUE TITLE
Update tandems on keyboardNav panel

### ISSUE THREAD

**Issue by zepumph** [phetsims/resistance-in-a-wire#103]
I noticed that many tandems were the same as other components, so RIAW was broken. I fixed the duplications by removing unneeded layout tandems, but there is still some work to be done. (1) Not all texts/icons have tandems, and (2) not all tandems are named appropriately.

1. When I make all instrumented items on the panel invisible, this is what I still see in instance proxies.
![image](https://user-images.githubusercontent.com/6856943/30993442-8bd87592-a45b-11e7-928d-bd0a9eee9ab5.png)
This makes me think that not every text/icon is instrumented.

2. PhET-iO tries to follow the convention that the tandem name is the same as the variable name like the following snippets:
```js

    var shiftTabKeyIcon = ResistanceInAWireKeyboardHelpContent.createShiftPlusIconHBox( new TabKeyNode( {
        minKeyWidth: TEXT_KEY_WIDTH,
        maxKeyWidth: TEXT_KEY_WIDTH,
        tandem: tandem.createTandem( 'shiftTabKeyIcon' )
    } ) );

    var shiftPlusTabDescription = new RichText( ResistanceInAWireA11yStrings.shiftTabKeyDescriptionString, _.extend( {
      tandem: tandem.createTandem( 'shiftPlusTabDescription' ),
      maxWidth: TEXT_MAX_WIDTH
    }, DESCRIPTION_OPTIONS ) );
```

Using the above convention this snippet is correct, but not ideal because these two items should have names that link them a bit better, either both with "Plus" or neither.

@jessegreenberg said he would look into this. Thanks!

**Comment by zepumph** [comment]
Also, yesterday we talked about only creating these items (which means registering these tandems too) if accessibility is enabled. Otherwise all of these needless tandems will be created even if accessibility isn't enabled, and there is no keyboard nav button.

**Comment by jessegreenberg** [comment]
In the above commit I made sure that all icons and descriptions have a tandem and that the tandem names follow convention and that icon and description tandem names are similar so that they are linked as suggested in https://github.com/phetsims/resistance-in-a-wire/issues/103#issue-261483987.

**Comment by jessegreenberg** [comment]
To address https://github.com/phetsims/resistance-in-a-wire/issues/103#issuecomment-333170089, a11y is now enabled by default in this sim since keyboard navigation is nearly ready for deployment.

**Comment by jessegreenberg** [comment]
I tested in instance-proxies and I think everything is working well. @zepumph could you please review?

**Comment by zepumph** [comment]
Looks really nice. Thanks for doing that. I'm not sure that we will need these layout tandems ever.

* `resistanceInAWire.keyboardHelpContent.sliderIconsVBox`
* `resistanceInAWire.keyboardHelpContent.sliderDescriptionsVBox`

But heck, I'm not really even sure that any of this needs to be instrumented. For now I would say it is good to go, we can always update it later. Thank you!
