### ISSUE TITLE
Readout values shrink with 4 digits

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/resistance-in-a-wire#105]
![capture](https://user-images.githubusercontent.com/6396244/31363694-617a741a-ad1d-11e7-969e-e4b70ae14a09.PNG)

I am not seeing this in the deployed version, looks new.

**Comment by jessegreenberg** [comment]
It looks like the max width used to be 
```
var MAX_TEXT_WIDTH = ResistanceInAWireConstants.SLIDERS_HORIZONTAL_SEPARATION * 0.90; // Max text width for labels
```

Now it is `ResistanceInAWireConstants.SLIDER_WIDTH`

**Comment by jessegreenberg** [comment]
SLIDERS_HORIZONTAL_SEPARATION used to be 115,  SLIDER_WIDTH is 60, that explains it.

**Comment by jessegreenberg** [comment]
When I change valueText maxWidth, the the slider track size changes, weird.

**Comment by zepumph** [comment]
I worked on this with @jessegreenberg today, we will probably need to redo more of the layout to account for double string test, but for now this was a quick fix. Increasing the slider_width constant fixes this. If we find that the layout is too wide for the control panel now, we should be able to decrease the hbox spacing to account for this increase. Back to you @jessegreenberg.

**Comment by jessegreenberg** [comment]
Thanks @zepumph I just compared against the spacing with 1.2.8 (latest deployed version) and the separation between the wire and the panel when length is maxed is almost identical so I don't think anything else needs to be done. Thanks for the help on this @zepumph, closing.
