### ISSUE TITLE
ControlPanel layout

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/resistance-in-a-wire#106]
While fixing #105, we noticed some slightly strange layout within the control panel for translated strings.
![capture](https://user-images.githubusercontent.com/6396244/31404108-585646d4-adb8-11e7-8343-a07df8fcaef6.PNG)

@zepumph and I tried a few different layout strategies including using different VBoxes, and AlignGroup with AlignBoxes.  But it didn't work out because the different slider components have no knowledge of each other. I order to perfectly align each row, we would like to change SliderUnit (or completely do away with it) so that the control panel can manage layout more directly.

@zepumph please fill in or correct any of this info if I am missing something.

@ariel-phet do you see this layout as problematic and do you think it is worth time fixing?

**Comment by jessegreenberg** [comment]
Here is the layout with default strings
![capture](https://user-images.githubusercontent.com/6396244/31404400-320f736e-adb9-11e7-8336-78dd41ee5797.PNG)

**Comment by ariel-phet** [comment]
@jessegreenberg yes we should fix these layout issues.

**Comment by jessegreenberg** [comment]
Ok, thanks. We should do this before the upcoming redeploys.

**Comment by jessegreenberg** [comment]
@zepumph here is what I am thinking:
Keep `SliderUnit`, but instead of making it responsible for layout, it just collects the components and provides an API to get them in the control panel.  Then, in the control panel we use getters to get valueText, unitText, and so on. The control panel could create some align boxes that guarantees that rows are aligned.

In control panel:
```js
var unitAlignBox = new AlignBox( { matchHorizontal: false } )
var resistanceUnitsBox = unitAlignBox.createBox( resistanceSliderUnit.unitsText );
var lengthUnitsBox = unitAlignBox.createBox( lengthSliderUnit.unitsText );
var areaUnitsBox = unitAlignBox.createBox( lengthSliderUnit.unitsText );

// vertically aligned units
var unitsHBox = new HBox( { children: [ resistanceUnitsBox, lengthUnitsBox, areaUnitsBox ] );
```

**Comment by jessegreenberg** [comment]
Alright, thanks Ill give it a shot.

**Comment by jessegreenberg** [comment]
Before using AlignGroup, I tried again to do the layout relative to the bottom text for consistency and it worked out.

![capture](https://user-images.githubusercontent.com/6396244/31470870-31c82ece-aea3-11e7-92cd-406bf283535f.PNG)

@zepumph would you please review? The remaining problem is with the unit text for stringTest=double, which I believe is a bounds problem with scenery RichText (https://github.com/phetsims/scenery/issues/687). @ariel-phet does this require a fix before the redeploy?

![capture2](https://user-images.githubusercontent.com/6396244/31470889-44f4d27c-aea3-11e7-983c-ed773b887aad.PNG)

In the deployed version, the ohmcm move down a little with stringTest=double as well:
https://phet.colorado.edu/sims/html/resistance-in-a-wire/latest/resistance-in-a-wire_en.html?stringTest=double

**Comment by zepumph** [comment]
Nice! I didn't realize that this was a know bug, and already in the published version. @jessegreenberg thanks for diving in again. To me it looks good.

**Comment by ariel-phet** [comment]
@jessegreenberg sorry I am a little unclear on what aspect this question is referring to?

> @ariel-phet does this require a fix before the redeploy?

**Comment by jessegreenberg** [comment]
Sorry, the slight misalignment of the bottom row of units text with `stringTest=double`, shown in the second image in https://github.com/phetsims/resistance-in-a-wire/issues/106#issuecomment-335970449.

**Comment by ariel-phet** [comment]
@jessegreenberg - a quick scan of the translations of the current published version show that the majority of the translations do not change the units. 

However, a few do, such as https://phet.colorado.edu/sims/html/resistance-in-a-wire/latest/resistance-in-a-wire_kn.html

You will see this slight misalignment is present in the published version (it seems acceptable)

So, it would be ideal to fix before redeploy, but my understanding is that you are under a fair bit of a time crunch to get more of these sims out. So skipping this fix would be acceptable, as it is not causing a major bug/horrible aesthetics.

**Comment by jessegreenberg** [comment]
Sounds great, thanks @ariel-phet. I think the fix will require work in https://github.com/phetsims/scenery/issues/687, so we will  see what @jonathanolson suggests before deciding.

**Comment by jessegreenberg** [comment]
@jonathanolson provided a recommendation that is working nicely in this case, thanks! 
![capture](https://user-images.githubusercontent.com/6396244/31507507-28320750-af38-11e7-93af-ff2f9e9deb1a.PNG)

**Comment by jessegreenberg** [comment]
Fixed in the above commit, this can be closed.

**Comment by zepumph** [comment]
@jessegreenberg @jonathanolson you two are heros. Thanks for cracking down on this. I think next Ohms Law will need to be handled in the same manner. I'll make an issue.
