### ISSUE TITLE
Should Reset All be able to move sliders that have been disabled?

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/resistance-in-a-wire#111]
For phetsims/QA#53

In instance proxies, I set the resistivity slider to its max of 1, and deselected its Enabled property `resistanceInAWire.resistanceInAWireScreen.view.controlPanel.resistivitySlider.slider.enabledProperty`. This allows you to only move the other two sliders when you launch the sim, but if you press reset all, even the disabled slider is reset to its default position. I imagine it would be useful to be able to force one of the values to remain constant, but you can change it by reseting, and you won't be able to get it back.

**Comment by phet-steele** [comment]
@brroberts1231 good question. The answer is here: https://github.com/phetsims/phet-io/issues/584.
The best solution for the end user is to disable the Reset All button, and that is documented for them to read. It's temporary, but does the trick.
