### ISSUE TITLE
Resistance symbol on stringTests disappears at high values

### ISSUE THREAD

**Issue by arnabp** [phetsims/resistance-in-a-wire#116]
On double and long string tests the symbol for resistance will disappear instead of filling the entire screen read, I assume because there is white space at the center of the symbol in those cases. I know we can't control whether there is white space in the center of this symbol for other languages, but I just wanted to make sure we're okay with this behavior? 

For phetsims/QA#66

![screen shot 2017-11-13 at 1 24 58 pm](https://user-images.githubusercontent.com/8583364/32747510-27340e96-c876-11e7-853a-3d9656db8ee1.png)

**Comment by jessegreenberg** [comment]
@ariel-phet I assume we are OK with this for the reasons mentioned in #113 (very few people translate the symbols and those that do will use single letters)?

**Comment by ariel-phet** [comment]
@jessegreenberg I went through all simulations, It seems that everyone is using a single letter (even if they change the symbol).

The only one that seems messed up is Tibetan, but it seems the translator did something odd, and still kept the symbols:

https://phet.colorado.edu/sims/html/resistance-in-a-wire/latest/resistance-in-a-wire_bo.html

**Comment by ariel-phet** [comment]
So yes, i think we are OK with this behavior, I am going to get Oliver to email the Tibetan translator to let them know.

**Comment by jessegreenberg** [comment]
Great, thanks. Closing  this issue. @arnabp thanks for bringing it up!
