### ISSUE TITLE
Focus incorrectly managed when using mouse + keyboard

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/resistance-in-a-wire#119]
From https://github.com/phetsims/QA/issues/73

@phet-steele found that this sim is susceptible to https://github.com/phetsims/scenery/issues/713. It is particularly obvious when interacting with the PhET menu. Steps to reproduce buggy behavior:

- Focus "Area" slider by tabbing to it.
- Open the PhET menu with a mouse.
- Focus highlight goes away
- Use arrow keys. Observe that the  Area slider moves.

**Comment by jessegreenberg** [comment]
Actually,  it looks like for this sim, this is a buggy implementation for the current implementation of handling keyboard + mouse interaction with the PhET menu. When the PhET menu is shown, we have

```js
        // make sure that any previously focused elements no longer have focus
        Display.focusProperty.set( null );
```

this removes the focus highlight, but does NOT blur the active element.

**Comment by jessegreenberg** [comment]
@phet-steele I believe this is resolved in master, would you please verify?

**Comment by phet-steele** [comment]
Verified!
