### ISSUE TITLE
"ohm" to be changed to "ohms" in visual sim

### ISSUE THREAD

**Issue by terracoda** [phetsims/resistance-in-a-wire#124]
As noted in issue #122,

While exploring final versions of descriptions and alerts in Jan 25th design meeting it was noted that using "ohm" is only correct when Resistance is actually 1, so it would be better if we use "ohms" in the visual and non-visual experiences.

Please change "ohm" to "ohms" in the visual sim.

**Comment by terracoda** [comment]
@ariel-phet, I just want to confirm that you are good with changing "ohm" to "ohms". My understanding from the design meeting was that would be good change to the visual sim.

**Comment by ariel-phet** [comment]
@terracoda yes, "ohms" would be preferable

**Comment by terracoda** [comment]
Thanks @ariel-phet. I will assign to @jessegreenberg now.

@jessegreenberg, please change "ohm" to "ohms" in the visual sim.

I will try to do a search and replace in the RIAW description google sheet. I am pretty sure I used "ohm" in there because of the visual design.

**Comment by terracoda** [comment]
@jessegreenberg, I cleaned up the google sheet. It has "ohms" now.

**Comment by jessegreenberg** [comment]
Change made in the above commit, in the english version the readout now says "ohms".
