### ISSUE TITLE
Rounding error found in visual sim

### ISSUE THREAD

**Issue by terracoda** [phetsims/resistance-in-a-wire#125]
As noted in issue #122,

While exploring edge cases with extreme slider values, I was able to see a zero value for Resistance even though a zero value is not actually possible since the sliders for resistivity, length and area do not have zero values.

This edge case happens when Length is at minimum, and Area is at maximum, and the user explores the Resistivity slider. Values for Resistance range only from 0 to 0.01 ohm, so for a good portion of the resistivity slide, Resistance shows as "resistance = 0.00"

In the description, we might need to say "near zero" rather than zero, and I am not sure exactly how we should fix the visual sim, or if we need to.

@emily-phet or @ariel-phet, could one of comment and assign to appropriate designer?

**Comment by ariel-phet** [comment]
@terracoda I think we could easily solve this issue by adding a third decimal place when the value of the resistance is less than 1.00. The sim already handles 4 digits (Length and Resistivity maximum, and Area minimum gives 2000 ohm resistance). We are playing a little fast and loose with significant digits but nobody seems to have minded. This seems like a simple change that could be made. 

If this is an acceptable solution, please just assign over to @jessegreenberg.

**Comment by terracoda** [comment]
@ariel-phet, if this solution means Resistance won't ever register as 0.000, that sounds good to me.

I will assign to @jessegreenberg. We can then see if an an extra zero will impact the visual layout.

**Comment by terracoda** [comment]
@jessegreenberg, please add a third decimal point when resistance is less than 1.00.

**Comment by terracoda** [comment]
@jessegreenberg, please re-assign to me if you have any design questions. I am un-assigning myself.

**Comment by jessegreenberg** [comment]
Change made in the above commit. @terracoda can you review? It is still possible for 0.000 to show up when R is smallest.

**Comment by jessegreenberg** [comment]
If we add a fourth decimal place then there will always be a value in the readout.

**Comment by terracoda** [comment]
@ariel-phet and @emily-phet, it looks like we have just enough visual space for another decimal place. I think it would be ideal if the fourth decimal place was also restricted - only added when resistance becomes less than 0.001. 

Here's an example edge case: the lowest 7 values for Resistivity where Length is at minimum and Area is at maximum produce values for Resistance lower than 0.000.

<img width="739" alt="screen shot 2018-02-07 at 22 04 28" src="https://user-images.githubusercontent.com/1902116/35950809-ec8179ac-0c52-11e8-8407-24792a90f6b7.png">

<img width="737" alt="screen shot 2018-02-07 at 21 54 42" src="https://user-images.githubusercontent.com/1902116/35950787-c8ba78a2-0c52-11e8-8b37-d07b477867cc.png">

Should another decimal place be added?

**Comment by ariel-phet** [comment]
As I mentioned, we don't seem to be sticking to pedantically to significant digit rules, and you can get a 4 digit resistance like 1990. So I think adding a 4th decimal in the less than 0.001 case is fine

An argument could be made for the resistance being "effectively" zero, which would be the other way to go when resistance is very small. But in this case, 0.0001 ohms is a perfectly measurable resistance, so I see no reason not to display it.

**Comment by jessegreenberg** [comment]
Thanks @ariel-phet and @terracoda, changed in the above commit. Closing.
