### ISSUE TITLE
Implement accessible descriptions in this sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/resistance-in-a-wire#126]
From #122, we are ready to add accessible description to this sim.

**Comment by terracoda** [comment]
Thanks for starting a new issue @jessegreenberg.

**Comment by jessegreenberg** [comment]
Implementation was completed with the above commits. I made an issue in https://github.com/phetsims/QA/issues/92 to test behavior. Closing this issue since new issues will be made during review and testing.
