### ISSUE TITLE
Uncaught Error: Assertion failed: Setting bottom is invalid when the node has invalid (empty/NaN/infinite) bounds. (stringTest=xss)

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/resistance-in-a-wire#128]
From #127 - once that issue was fixed I started to see this error when running with stringTest=xss.
```
Uncaught Error: Assertion failed: Setting bottom is invalid when the node has invalid (empty/NaN/infinite) bounds.
```

**Comment by jessegreenberg** [comment]
It is complaining about this:
```js
    var symbolText = new Text( symbolString, {
      font: ResistanceInAWireConstants.SYMBOL_FONT,
      fill: ResistanceInAWireConstants.BLUE_COLOR,
      maxWidth: ResistanceInAWireConstants.SLIDER_WIDTH,
      boundsMethod: 'accurate',
      tandem: tandem.createTandem( 'symbolText' )
    } );
```

**Comment by jessegreenberg** [comment]
When I remove `boundsMethod`, the problem goes away. Also when I use RichText instead of Text the problem goes away.

**Comment by jessegreenberg** [comment]
I tried looking through `Text.js` and `setBoundsMethod`, but nothing is jumping out. @jonathanolson does this issue ring any bells?

**Comment by jessegreenberg** [comment]
This problem is not showing up in continuous testing... hmm

**Comment by jessegreenberg** [comment]
After 24 hours, this isn't showing up in continuous testing. I am still unable to run sim locally with stringTest=xss.

**Comment by jessegreenberg** [comment]
Bug is there in phettest.

**Comment by jessegreenberg** [comment]
According to the RC checklist:
>stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)

Is this a non issue? @jonathanolson is that why this isn't tested in CT?

Since the sim crashes and doesn't redirect, I am going to proceed with the RC for this sim.

**Comment by jonathanolson** [comment]
> Is this a non issue? @jonathanolson is that why this isn't tested in CT?

It's not tested in CT yet because it's extra effort to program in the checks for it. I don't see why stringTest=xss couldn't be included, but given how often failures happen, I'm not sure about whether the effort would be worth it.

> Since the sim crashes and doesn't redirect, I am going to proceed with the RC for this sim.

Sounds fine. It may be a sign that if you put in a super-long or super-short string in the failure point it may also fail, but it's probably nothing important.

There may have been something mis-positioned so that it cascades and something gets set to invalid bounds.

**Comment by zepumph** [comment]
From the code review checklist:
> Does the sim stay on the sim page (doesn't redirect to an external page) when running with the query parameter stringTest=xss? This test passes if sim does not redirect, OK if sim crashes or fails to fully start. Only test on one desktop platform.

Are we ready to close this issue?

**Comment by jessegreenberg** [comment]
I think so @zepumph , thanks.
