### ISSUE TITLE
(JAWS) multiple readouts per increment

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#131]
**Test device:**

Hanson

**Operating System:**

Windows 10

**Browser:**

Firefox ESR

**Problem description:**

When increasing or decreasing resistivity, length, or area, JAWS will read multiple values for a single increase or a single decrease. For example, I'll increase length from 10.00 cm to 11.00, and JAWS will say "11.00 cm, to increase or decrease use the arrow keys, 11.00 cm." It will sometimes say "11.00 cm, 11.00 cm, to increase or decrease use the arrow keys." Will investigate more tomorrow. This is for phetsims/QA/issues/92.

**Steps to reproduce:**

Increase or decrease resistivity, length, or area.

**Troubleshooting information (do not edit):**

Name: ‪Resistance in a Wire‬
URL: https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.5.0-dev.1/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-dev.1 2018-02-09 20:00:00 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0
Language: en-US
Window: 1280x611
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"e1350857","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"10125b6e","branch":"master"},"dot":{"sha":"8d471f40","branch":"master"},"joist":{"sha":"5567ef56","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"f35ff65e","branch":"master"},"phet-io":{"sha":"59e4fea1","branch":"master"},"phet-io-website":{"sha":"766da99e","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"master"},"phet-io-wrapper-sonification":{"sha":"c276b0fa","branch":"master"},"phet-io-wrapper-visualizing-engagement":{"sha":"92165486","branch":"master"},"phet-io-wrappers":{"sha":"d79148b8","branch":"master"},"phetcommon":{"sha":"d33be800","branch":"master"},"query-string-machine":{"sha":"485e174e","branch":"master"},"resistance-in-a-wire":{"sha":"5031adb2","branch":"master"},"scenery":{"sha":"c1725c3e","branch":"master"},"scenery-phet":{"sha":"666a80bb","branch":"master"},"sherpa":{"sha":"7a6906fd","branch":"master"},"sun":{"sha":"b854de6b","branch":"master"},"tandem":{"sha":"63c71e1a","branch":"master"}}

**Comment by phet-steele** [comment]
@jessegreenberg it was part of #132, not technically the "same". But yes it can be closed.
