### ISSUE TITLE
resistance readout shouldn't go to zero

### ISSUE THREAD

**Issue by jbphet** [phetsims/resistance-in-a-wire#134]
I'm working on sonification of the sim, and one of the challenges is to map the huge range of resistance values to pitch values.  It seems like perhaps the range to *too* large, since it causes the readout to go to zero, as shown in the screen shot below.  Zero resistance is a real thing in superconductivity, but we are showing zero resistance in a normal, presumably room-temperature wire, which is physically incorrect.

![image](https://user-images.githubusercontent.com/3082831/36609967-e4e38e02-188b-11e8-8ec2-9ecf211d8ffa.png)

**Comment by jbphet** [comment]
Assigning to @ariel-phet to decide if we should do something about this.  One solution would be to revise the range, another would be to show more digits (perhaps dynamically).

**Comment by phet-steele** [comment]
@jbphet the readout was updated to three decimal places. See https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.5.0-dev.1/phet/resistance-in-a-wire_en_phet.html

**Comment by phet-steele** [comment]
@jbphet maybe you are stale or maybe the commits were only in a branch, but the issue is here: https://github.com/phetsims/resistance-in-a-wire/issues/125

**Comment by jbphet** [comment]
I'm using an older phet-io version.  Glad to hear it's been resolved - closing.
