### ISSUE TITLE
Slightly re-work general cue to find Keyboard Shortcuts more easily

### ISSUE THREAD

**Issue by terracoda** [phetsims/resistance-in-a-wire#136]
Based on user feedback, visually impaired users may benefit from some instructions on where to actually find the Keyboard Shortcuts button.

Current cue is:
- "If needed, checkout keyboard shortcuts for this sim."

Iterations:
1. "If needed, checkout keyboard shortcuts at bottom of sim."
2. "If needed, checkout keyboard shortcuts at bottom of sim, under Sim Resources and Tools."

I think example one should do it.

Anythoughts, @emily-phet?

**Comment by terracoda** [comment]
Oops, sorry, I didn't see duplicate.

**Comment by terracoda** [comment]
@jessegreenberg and @emily-phet, I can't think of any reason why this small change would be a bad idea.

**Comment by jessegreenberg** [comment]
Seems fine to me @terracoda. Just throwing out an alternative
"If needed, check out keyboard shortcuts in the navigation bar."

Is it important that it say "bottom of sim"? "navigation bar" sounds nicer and more accurate to me but I don't feel strongly.

**Comment by terracoda** [comment]
@jessegreenberg, that is a very reasonable suggestion. I also considered that, but we don't have any content or ARIA role in the sim right now that communicates "navigation bar". How is a blind user to know if the navigation bar is at the beginning or end of the sim? I guess they could rule out beginning because they are at the beginning.

Added Iterations to the first list:
1.  "If needed, checkout keyboard shortcuts at bottom of sim."
2. "If needed, checkout keyboard shortcuts at bottom of sim, under Sim Resources and Tools."
3.  "If needed, check out keyboard shortcuts in the navigation bar."
4.  "If needed, check out keyboard shortcuts in bottom navigation bar."
5. "If needed, checkout keyboard shortcuts under Sim Resources and Tools." 
  - or multi-screen sims, "If needed, checkout keyboard shortcuts under Sim Screens, Resources and Tools."

**Comment by jessegreenberg** [comment]
Discussed in 3/6/18 keyboard navigation meeting. Together, we came up with this:
"If needed, checkout keyboard shortcuts under sim resources."

We will use this for now, but we also discussed restructuring the accessible HTML of the navigation bar to put sim screens in a navigation section and the help dialog and PhET menu in a "resources" region.

**Comment by jessegreenberg** [comment]
String has been changed.

**Comment by terracoda** [comment]
@jessegreenberg, when you change and commit the string, can you be sure to change the h2 heading, "Sim Resources and Tools" to "Sim Resources".

I just listened on PhET Test and didn't hear the change in either place.  Maybe you still need to commit.

**Comment by jessegreenberg** [comment]
Sure, Ill change the H2 as well, thanks @terracoda.

**Comment by jessegreenberg** [comment]
OK, both strings were updated. Closing this issue.
