### ISSUE TITLE
Double check that sliders have a vertical orientation set with aria-

### ISSUE THREAD

**Issue by terracoda** [phetsims/resistance-in-a-wire#137]
In a recent interview where RIAW and OL were explored, a JAWS user identified the sliders as horizontal sliders, and the participant commented "I'll use the right left arrow keys".

While all the Arrow keys work regardless of orientation it was not an issue for the user.

However, it is likely beneficial for students that vertical sliders are identified as vertical sliders. The horizontal orientation is the default orientation.

When I use Voice Over, I do not hear anything about orientation of the RIAW sliders. The participant was using JAWS, did.

In this example from whatsock.com, I do hear, "vertical slider"
http://whatsock.com/tsg/Coding%20Arena/ARIA%20Sliders/Vertical/demo.htm

Here's the link to the specification:
https://www.w3.org/TR/wai-aria-1.1/#aria-orientation

**Comment by terracoda** [comment]
Just noticed that that in Aria 1.1, the implicit default is undefined.

**Comment by jessegreenberg** [comment]
Sounds good @terracoda, aria-orientation is currently not used. Ill add it to sun's AccessibleSlider.

**Comment by jessegreenberg** [comment]
AccessibleSlider now supports aria-orientation and it has been used in resistance-in-a-wire. Closing  this issue @terracoda.

**Comment by terracoda** [comment]
Thanks @jessegreenberg!
