### ISSUE TITLE
aria-orientation attribute prevents JAWS from entering forms mode automatically 

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/resistance-in-a-wire#138]
@lmulhall-phet found this for https://github.com/phetsims/QA/issues/108. When using tab to focus on a slider JAWS does not enter forms mode automatically. You have to press "enter" to enter forms mode, then you can use the arrow keys to interact with the slider.

This is a problem for 1.5.0-rc.1, but NOT a problem for 1.5.0-dev.1. The only change between the two versions (other than some minor string changes) is the addition of the `aria-orientation` in rc.1.

We verified the bug outside of PhET in https://jsfiddle.net/3azLv45n/2/

@terracoda is it still OK to use aria-orientation with this JAWS bug?

**Comment by jessegreenberg** [comment]
IMO we should keep using aria-orientation in spite of this JAWS inconsistency. JAWS users rarely navigate with "tab" anyway,  and would generally know to press "enter" to activate forms mode.  It is just very odd that JAWS doesn't enter forms mode automatically with aria-orientation.

**Comment by terracoda** [comment]
I agree, it is odd that JAWS does not enter forms mode automatically with aria-orientation, but I agree with @jessegreenberg that we should stick with using aria-orientation to communicate the orientation. It may be different with younger users, but in my last 3 interviews with adult JAWS users, none had JAWS set to the default auto-forms mode.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, sounds good to me. I am going to close this issue and make a note of this for future tests.
