### ISSUE TITLE
Exiting keyboard navigation unhighlights keyboard navigation button

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#141]
Win 10 / Edge: Pressing enter when exiting the keyboard navigation help dialogue unhighlights the keyboard navigation button. Seen on Hanson. Related to phetsims/QA/issues/108.

EDIT: Same thing with space bar.

Troubleshooting information (do not edit):
Name: ‪Resistance in a Wire‬
URL: https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.5.0-rc.1/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-rc.1 2018-03-09 23:10:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
Language: en-US
Window: 1280x603
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"cc053b4d","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"54f17be2","branch":"HEAD"},"dot":{"sha":"0dd6ee8e","branch":"HEAD"},"joist":{"sha":"9ca4cd0a","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"d54be499","branch":"HEAD"},"phet-io-website":{"sha":"28284828","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrappers":{"sha":"ce57c3e2","branch":"HEAD"},"phetcommon":{"sha":"a5a7478c","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"resistance-in-a-wire":{"sha":"39b3ad26","branch":"HEAD"},"scenery":{"sha":"ddef8aa5","branch":"HEAD"},"scenery-phet":{"sha":"42b0cff2","branch":"HEAD"},"sherpa":{"sha":"9c6ec322","branch":"HEAD"},"sun":{"sha":"6a7c923a","branch":"HEAD"},"tandem":{"sha":"7f499d9e","branch":"HEAD"}}

**Comment by EthanWJohnson** [comment]
Interesting note: it actually briefly re-highlights the keyboard help button after exiting the help dialog but un-highlights it immediately after. The keyboard navigation is then completely reset to the starting position in the sim, which appears to be the resistivity slider.

**Comment by jessegreenberg** [comment]
I isolated that this is caused by https://github.com/phetsims/scenery/commit/65a1f0828c606ab668457a0a4774b948e7d03b4a for https://github.com/phetsims/a11y-research/issues/30. Since I added this work around, Ill try to fix this issue.

**Comment by jessegreenberg** [comment]
I believe this is fixed with the above commit. Release branch will need a release branch for scenery with the cherry-picked commit https://github.com/phetsims/scenery/commit/d27f8465ee73a00489b3431ca95ff51c07282292

**Comment by lmulhall-phet** [comment]
Fixed! Closing.
