### ISSUE TITLE
Screen reader reading wrong tense of "read"

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#146]
For phetsims/QA/issues/118. This is slightly nitpicky, but...

On VoiceOver with Safari, the word "read" is read the wrong way.

> Look for resistivity, length, and area sliders to play, or read on for details about equation and wire.

Current pronunciation: past tense read as in red
Desired pronunciation: present tense read as in reed

Is there any way to specify which tense you'd like the screen reader to choose?

@jessegreenberg and @terracoda, do either of you have any suggestions?

**Comment by zepumph** [comment]
I am not sure what the priority is for this, but https://www.levelaccess.com/zip-z-p-z-p-forcing-correct-pronunciation-screen-readers/ says that it is generally acceptable have to mispronunciations with screen readers, and the forcing it (at least with acronyms) can be a tricky and finicky. @emily-phet what do you think this priority is?

**Comment by zepumph** [comment]
This too doesn't seem too helpful, but is talking about just this problem, http://lab.dotjay.com/tests/screen-readers/pronunciation/read/

**Comment by zepumph** [comment]
@lmulhall-phet is this consistent across other supported browsers?

**Comment by lmulhall-phet** [comment]
@zepumph, no. JAWS and NVDA read "read" correctly.

**Comment by phet-steele** [comment]
@zepumph for the record, the Karen voice package says this word correctly.

**Comment by zepumph** [comment]
Sounds good, from what I'm hearing, this seems like a small/non issue, but it isn't my call.

**Comment by terracoda** [comment]
@lmulhall-phet, re https://github.com/phetsims/resistance-in-a-wire/issues/146#issue-325492906 the accuracy of pronunciation seems to be voice specific. We can not control the pronunciation from our end. Screen reader users are generally aware of the inaccuracies of their preferred voice.

**Comment by lmulhall-phet** [comment]
Thanks, @terracoda! I think we can close this issue if no one objects.
