### ISSUE TITLE
Adjusting Length in Larger Steps Creates odd Increments

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/resistance-in-a-wire#152]
Test device: PC Laptop / PC Laptop / MacBook Pro

Operating System: Windows 10 OS 17134.81 / Windows 10 OS 17134.81 / macOS High Sierra v. 10.13.4

Browser: Chrome v. 67.0.3396.62 / Firefox v. 60.0.1 / Chrome v. 66.0.3359.181

Problem description: For phetsims/QA#125 when using keyboard shortcuts and adjusting length in larger steps the value is incremented by 1.99 rather than 2.0. Once the value has been incremented in this way and then adjusted via normal adjustments the value does not increment by 1.0 but moves to the next integer.

Steps to reproduce: 
1. Using the tab button move to the length slider
2. Adjust in larger steps by using either pg up or pg down
3. The slider will adjust by 1.99 rather than 2.0

Screenshots:
![riaw_increment](https://user-images.githubusercontent.com/30352536/40853204-79eb3018-658a-11e8-81a6-9a13a809d6f1.gif)

<details> 
<summary> Troubleshooting Info: </summary>
Troubleshooting information (do not edit):
Name: ‪Resistance in a Wire‬
URL: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.5.0-rc.5/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-rc.5 2018-05-31 01:31:21 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
Language: en-US
Window: 958x994
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"cc053b4d","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"54f17be2","branch":"HEAD"},"dot":{"sha":"0dd6ee8e","branch":"HEAD"},"joist":{"sha":"f047fb1b","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"d54be499","branch":"HEAD"},"phet-io-website":{"sha":"28284828","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrappers":{"sha":"ce57c3e2","branch":"HEAD"},"phetcommon":{"sha":"a5a7478c","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"resistance-in-a-wire":{"sha":"f80c6036","branch":"HEAD"},"scenery":{"sha":"33290b5e","branch":"HEAD"},"scenery-phet":{"sha":"42b0cff2","branch":"HEAD"},"sherpa":{"sha":"9c6ec322","branch":"HEAD"},"sun":{"sha":"6a7c923a","branch":"HEAD"},"tandem":{"sha":"7f499d9e","branch":"HEAD"}}\
</details>

**Comment by zepumph** [comment]
We defined the pg up and pg down specifically to divide the range into 10 (.10 - 20), hence the "weird" decimal logic. @jessegreenberg can you confirm and close if you agree.

**Comment by jessegreenberg** [comment]
@zepumph @JRomero0613 that is correct, the decision was to make larger steps fro each slider be 1/10th of the range, though it results in strange value deltas.
