### ISSUE TITLE
[keyboard navigation] On Chrome OS, moving slider then pressing shift stops slider

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#156]
<b>Test Device</b>

Feynman

<b>Operating System</b>

Chrome OS Version 68.0.3440.25

<b>Browser</b>

Chrome

<b>Problem Description</b>

For phetsims/QA/issues/130. If you try to press shift as you're moving a slider, the slider will stop. The slider is not, however, stuck.

I don't think this is a huge issue; it doesn't affect the functionality of the simulation. I'm wondering if we care about this. @zepumph, what are your thoughts? 

<b>Steps to Reproduce</b>

1. Move a slider to the top.
2. Start moving the slider down.
3. As you're moving the slider down, press shift. (You should notice the slider stop.)

<b>Visuals</b>

This is the behavior on macOS with Chrome. Notice how the slider slows down toward the end of the gif. This is because I press shift. If I do this on Chrome OS, the slider simply stops.

![riaw](https://user-images.githubusercontent.com/31285590/41559009-fcb53980-72ff-11e8-956a-4734e46fcda6.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Resistance in a Wire‬
URL: https://bayes.colorado.edu/dev/html/resistance-in-a-wire/1.5.0-rc.6/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-rc.6 2018-06-14 20:52:34 UTC
Features missing: generatedcontent
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (X11; CrOS aarch64 10718.22.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.25 Safari/537.36
Language: en-US
Window: 1536x727
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 96)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"cc053b4d","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"fe3cb370","branch":"HEAD"},"dot":{"sha":"0dd6ee8e","branch":"HEAD"},"joist":{"sha":"f047fb1b","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"d54be499","branch":"HEAD"},"phet-io-website":{"sha":"28284828","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrappers":{"sha":"ce57c3e2","branch":"HEAD"},"phetcommon":{"sha":"a5a7478c","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"resistance-in-a-wire":{"sha":"9a2b480e","branch":"HEAD"},"scenery":{"sha":"33290b5e","branch":"HEAD"},"scenery-phet":{"sha":"42b0cff2","branch":"HEAD"},"sherpa":{"sha":"9c6ec322","branch":"HEAD"},"sun":{"sha":"6a7c923a","branch":"HEAD"},"tandem":{"sha":"7f499d9e","branch":"HEAD"}}

</details>

**Comment by zepumph** [comment]
@lmulhall-phet it is my understanding that is expected browser behavior. When you hold down a key for multiple events, it will continue firing until another keydown event overrides it. Closing. @jessegreenberg please reopen if you feel different.y
