### ISSUE TITLE
[Keyboard Navigation] Should slider thumb interact with mouse during keyboard navigation?

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#161]
For phetsims/QA/issues/137.

When you mouse over or drag a slider thumb, it becomes light grey.

![riaw](https://user-images.githubusercontent.com/31285590/42349559-63d1bac2-806a-11e8-9390-805cc306ed22.gif)

In the gif, I put the cursor on the slider, and then move the slider thumb over the cursor, so the slider thumb becomes light grey. However, because the cursor disappears, it looks like the slider thumb is changing color for no reason.

Are we OK with this?

I've seen this on all browsers on macOS.

**Comment by zepumph** [comment]
@lmulhall-phet I feel like this falls under that keyboard/mouse intersection that we currently aren't diving into (see https://github.com/phetsims/scenery/issues/713). @jessegreenberg  please reopen if you disagree.
