### ISSUE TITLE
fuzzMouse broken on 1.5 branch since rc.4

### ISSUE THREAD

**Issue by zepumph** [phetsims/resistance-in-a-wire#162]
https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.5.0-rc.4/phet/resistance-in-a-wire_all_phet.html?fuzzMouse works, but all later versions (current version rc.7) do not. Tagging @lmulhall-phet because he found the bug.

**Comment by zepumph** [comment]
When I diff the dependencies, I find that the error creeped in when bumping scenery from 
https://github.com/phetsims/scenery/commits/64f0c409873154d17998c0a149ffbec95daf270a to
https://github.com/phetsims/scenery/commits/33290b5e78b38bd33456cc2cb3f2919f2252c899

Notice that all those commits were in regards to https://github.com/phetsims/resistance-in-a-wire/issues/148#issuecomment-392137608

@jonathanolson I think it is ok if fuzzMouse is broken for this RC, but I think this deserves another spot check from you to make sure that more isn't broken. I tried to give you as much of a paper trail as possible. Will you please sign off on the commits cherry-picked in the above issue #148 and let me know if you think this is safe to proceed. 

Note that in the past 3 rc version, this fuzzMouse issue has been the only issue reported that seems to be at all related to these cherry-picked commits in scenery.

**Comment by jonathanolson** [comment]
> but I think this deserves another spot check from you to make sure that more isn't broken

This seems like mostly manual testing. Can we rely on QA, or is there something I should be doing?

**Comment by lmulhall-phet** [comment]
@zepumph, I'm happy to do whatever testing needs to be done. (Should I just verify that I can use fuzzMouse with RC versions greater than 4?) I need to verify that #159 is resolved before I can finish phetsims/QA/issues/137.

**Comment by zepumph** [comment]
I think that sounds like a good plan. @lmulhall-phet plan on fuzzMouse to be broken on this release branch, but (obviously) report anything else as an issue. If you find that you need fuzzMouse to truly test this release candidate, please let me know and @jonathanolson and I can see about fixing it (I'm not sure about the time commitment there).

**Comment by zepumph** [comment]
>Should I just verify that I can use fuzzMouse with RC versions greater than 4?

Right now none of these versions will have a working fuzzMouse, so I'm not sure what you mean.

**Comment by lmulhall-phet** [comment]
@zepumph, I must be taking crazy pills. Completely misread your comment. Let me know if you want anything tested.

**Comment by zepumph** [comment]
I feel convinced that any issues in this rc will be covered by QA, and don't need fuzzMouse in this branch. Closing
