### ISSUE TITLE
About dialog goes off screen if stringTest=double

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#172]
**Test device:**
Dell Laptop and Chromebook
**Operating System:**
Win 10 and Chrome OS
**Browser:**
Chrome
**Problem description:**
For phetsims/QA/issues/179
When stringTest=double the "about" dialog becomes larger and go partly or entirely off the screen.  If it becomes too large the close button goes off the screen.  I did go and check a published sim and saw this problem in Balancing Chemical Equations.  Not sure if this is a problem, so marking as a question as well.
**Steps to reproduce:**
1. Set stringTest=double
2. Go to the PhET menu
3. Select About

**Screenshots:**
Normal:
![normal](https://user-images.githubusercontent.com/41024075/44605671-8191e780-a7a7-11e8-92ea-91002750ad61.PNG)
Double:
![double](https://user-images.githubusercontent.com/41024075/44605683-8bb3e600-a7a7-11e8-9b9a-97d93973d20d.PNG)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Resistance in a Wire‬
URL: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.5.0-rc.8/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-rc.8 2018-08-23 22:07:53 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"cc053b4d","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"fe3cb370","branch":"HEAD"},"dot":{"sha":"56c1d4b8","branch":"HEAD"},"joist":{"sha":"f047fb1b","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"d54be499","branch":"HEAD"},"phet-io-website":{"sha":"28284828","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrappers":{"sha":"ce57c3e2","branch":"HEAD"},"phetcommon":{"sha":"a5a7478c","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"resistance-in-a-wire":{"sha":"b70a62da","branch":"HEAD"},"scenery":{"sha":"33290b5e","branch":"HEAD"},"scenery-phet":{"sha":"42b0cff2","branch":"HEAD"},"sherpa":{"sha":"9c6ec322","branch":"HEAD"},"sun":{"sha":"2e7beb55","branch":"HEAD"},"tandem":{"sha":"7f499d9e","branch":"HEAD"}}

</details>

**Comment by jessegreenberg** [comment]
Interesting, and not sim specific. I thought that our credits strings were not translatable and therefore didn't get doubled.

**Comment by zepumph** [comment]
I poked around Dialog and didn't see any height validation, ensuring that things aren't bigger that the screen. I'm unsure that it is Dialog's job to do this though. 

@jessegreenberg I looked into the doubling, and it is because CreditsNode uses a pattern for all of the strings, so the pattern is doubled. 

I will create an issue in joist to note this. @ariel-phet do you think that this is something that needs to be worked on for the publication of Resistance In a Wire (since it won't likely happen in the wild).

**Comment by zepumph** [comment]
SEE https://github.com/phetsims/joist/issues/516 for general issue.

**Comment by ariel-phet** [comment]
@zepumph this should not need to be worked on for RIAW publication, since we sort of "hand code" the about dialog and it is not available for translation (the names anyhow)

@KatieWoe thanks for pointing this out, now that there is a general issue, closing this one.
