### ISSUE TITLE
screenTest=double overlaps itself on iOS

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#173]
**Test device:**
iPad Air 2
**Operating System:**
iOS 11.4.1
**Browser:**
Safari 11
**Problem description:**
For phetsims/QA/issues/179
When stringTest=double the red heading in the slider box that displays the current resistance overlaps itself instead of becoming longer.  Moving the slider corrects this.
**Steps to reproduce:**
1. On an iPad Air 2 go to the sim
2. Use stringTest=double
3. Examine the string that gives the current resistance

**Screenshots:**
![img_0171](https://user-images.githubusercontent.com/41024075/44676600-09b6fd80-a9f1-11e8-9749-fcae0020b0fd.PNG)

**Comment by KatieWoe** [comment]
Edit: This is also occurring on iPad 4 iOS 10.3.3

**Comment by phet-steele** [comment]
@KatieWoe allow me to introduce you to https://github.com/phetsims/scenery/issues/469. This is more likely a problem with the stringTest, and not something a translator will ever see.

**Comment by rea-laura** [comment]
Also found on https://github.com/phetsims/QA/issues/219

**Comment by KatieWoe** [comment]
In https://github.com/phetsims/QA/issues/219 I've also seen this on Mac 10.14 safari.
https://drive.google.com/file/d/1nNpEemZUPqnTP4IhILr-9xQ23KHj_5Xk/view?usp=sharing
