### ISSUE TITLE
Is the read out for minimum length supposed to be 0.00...01?

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#177]
Here's what JAWS sounds like when it reads the "Slider Controls" h3:

https://drive.google.com/open?id=1-IBXvhnGrQo0n4jlHKwDEd5MomSDyFMl

For ~~https://github.com/phetsims/QA/issues/179~~ https://github.com/phetsims/QA/issues/183.

**Comment by jessegreenberg** [comment]
That sounds incorrect, its reading the value of the "Length" slider, and it sounds like the formatting isn't right.

**Comment by jessegreenberg** [comment]
Oh, for some reason it is reading the "min" and "max" values for the slider? I have never heard that before. he min value in the PDOM is  `min="0.1"`, so I am confused about where it is getting "0.00000.....1.

**Comment by jessegreenberg** [comment]
Hearing the recording again, it is saying "min 0.100...001", so it is a precision issue maybe.

**Comment by jessegreenberg** [comment]
Likely a problem with AccessibleSlider so assigning to myself.

**Comment by jessegreenberg** [comment]
I don't see anywhere where the "min" attribute could pick up extra decimals in `toFixed` calls or something, inspection in the console shows that min value is `0.1`.

I am not hearing this in JAWS with FF 62, but JAWS isn't reading min and max values for the slider when it receives focus. Ill see if I can figure out how to turn that on in user settings or something.

**Comment by jessegreenberg** [comment]
OK, I hear it now, only happens when reading through with the virtual cursor (not on focus). Here is the HTML for the slider:
```html
<label tabindex="-1" id="label-247-310-321-388-387-386-346-349" for="247-310-321-388-387-386-346-349">L, Length</label>
<input style="width: 1px; height: 1px;" id="247-310-321-388-387-386-346-349" tabindex="0" role="slider" aria-orientation="vertical" step="0.1" min="0.1" max="20" aria-valuetext="10.00 centimeters" type="range">
```

Ill try to reproduce in a JSFiddle.

**Comment by jessegreenberg** [comment]
I was able to reproduce in this JSFiddle: https://jsfiddle.net/au7rhbg8/

**Comment by jessegreenberg** [comment]
Seems to just happen for some "min" values for sliders. For example, this slider with min=0.3 reads the min value (**only when using the virtual cursor**) as "0.299999....". I think that we should submit a bug report to VFO, add to the list of AT quirks, and close this issue.

@terracoda @zepumph what do you think?

**Comment by jessegreenberg** [comment]
Here is a very basic slider where the bug is coming up, Ill probably use this one in the bug report.

**Comment by jessegreenberg** [comment]
I went ahead and reported https://github.com/FreedomScientific/VFO-standards-support/issues/112. I documented in our internal tracking. OK to close this issue?

**Comment by lmulhall-phet** [comment]
If you think we’re done, then it’s OK to close from QA’s standpoint. But perhaps @terracoda and @zepumph will have something to say, so I’ll leave it open for now.

**Comment by zepumph** [comment]
Sounds good to close. @jessegreenberg isn't there a place to document this sort of weirdness so qa has a list of know bugs to check before submitting issues to developers? I would recommend adding this there.

**Comment by jessegreenberg** [comment]
There is, sorry I mentioned in an edit to https://github.com/phetsims/resistance-in-a-wire/issues/177#issuecomment-419655417 that I added a note there.

**Comment by jessegreenberg** [comment]
Alright we have 👍 s from everyone so I think we can close!

**Comment by KatieWoe** [comment]
Does happen in https://github.com/phetsims/QA/issues/476, but not always consistently.

**Comment by KatieWoe** [comment]
https://drive.google.com/file/d/1hexjqYRExi6u7Doq8CGbOSHKlDqNFM3y/view?usp=sharing
Seen with values in https://github.com/phetsims/QA/issues/582 when tick marks are on.

**Comment by zepumph** [comment]
Sounds right, I don't see any progress on the Freedom Scientific issue.
