### ISSUE TITLE
Incorrect increment jumps on length and area sliders.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#179]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/183 during confirmation of https://github.com/phetsims/resistance-in-a-wire/issues/160.
When the normal keyboard nav up or down arrows are pressed they are meant to take the slider to the nearest whole number (example: pressing up when at 9.99 should take you to 10).  This is the behavior in the published sim.  However, in the rc, if the current number is between X.51 and X.99 the up arrow will take the slider to a number one higher than intended and if it is between X.01 and X.49 pressing the down arrow will take the slider to a number one lower than intended.
**Steps to reproduce:**
1. Use keyboard nav to control the length slider.
2. Use shift + up to move the number to 10.01.
3. Use the simple down arrow.  The slider will jump to 9 rather than 10.
4. Use shift + down to move the number to 8.99.
5. Use the simple up arrow.  The slider will jump to 10 rather than 9.
6. Compare the behavior to the behavior of the published sim with the same steps taken.

**Troubleshooting information (do not edit):**

<details>

Name: ‪Resistance in a Wire‬
URL: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.5.0-rc.9/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-rc.9 2018-09-06 18:39:48 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"cc053b4d","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"fe3cb370","branch":"HEAD"},"dot":{"sha":"56c1d4b8","branch":"HEAD"},"joist":{"sha":"f047fb1b","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"d54be499","branch":"HEAD"},"phet-io-website":{"sha":"28284828","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrappers":{"sha":"ce57c3e2","branch":"HEAD"},"phetcommon":{"sha":"a5a7478c","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"resistance-in-a-wire":{"sha":"87930562","branch":"HEAD"},"scenery":{"sha":"a7a0ca9e","branch":"HEAD"},"scenery-phet":{"sha":"42b0cff2","branch":"HEAD"},"sherpa":{"sha":"9c6ec322","branch":"HEAD"},"sun":{"sha":"2e7beb55","branch":"HEAD"},"tandem":{"sha":"7f499d9e","branch":"HEAD"}}

</details>

**Comment by jessegreenberg** [comment]
This should be fixed in master, @KatieWoe could you please check?

**Comment by KatieWoe** [comment]
@jessegreenberg This issue seems ok on master, but https://github.com/phetsims/resistance-in-a-wire/issues/160 seems to be back.  Most noticeable on resistivity and area sliders.

**Comment by jessegreenberg** [comment]
Thanks for testing that @KatieWoe, the problem was in the sim instead of AccessibleSlider this time. I did some checking but can you please make sure all is well?

**Comment by KatieWoe** [comment]
@jessegreenberg all looks good.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, closing this issue given #178
