### ISSUE TITLE
Reduce the amount of motion in the control panel title as the resistance changes

### ISSUE THREAD

**Issue by jbphet** [phetsims/resistance-in-a-wire#181]
@emily-phet said in #180:

> [@ariel-phet] also mentioned that the resistance word is moving on the screen now that there are three decimal places. He would like that word fixed in place. Is that something you can do?

and

> [@ariel-phet and @kathy-phet] would like something done to minimize the amount of 'jumping around' the resistance word does as the resistance value changes. Then it's good to go to move on to the next steps toward publication.

I'm creating this issue as a place to track commits made to address this "jumping around" problem.

**Comment by jbphet** [comment]
I just reviewed the revised behavior with @ariel-phet and he approved.  This will be included in the next release.  Closing.

**Comment by jbphet** [comment]
Reopening so that it can be verified on multiple platforms during the 1.6 release testing.

**Comment by phet-steele** [comment]
@jbphet "resistance" doesn't budge at all on my Win 10 Chrome! Although it does budge when using `?stringTest=double`.

**Comment by JRomero0613** [comment]
In testing I have noticed that "resistance" doesn't move at all when sliders are adjusted for values either below 1, or above 1. I think that this is because the motion in the "resistance" word occurs when changing from three decimal places to two as occurs when transitioning from R less than 1 to R greater than 1 or vice versa.

**Comment by KatieWoe** [comment]
@jbphet I'm seeing a bit of motion on Win 10 firefox.  Not sure how pronounced it was before so posting a video here to determine acceptability.
![jumpresist](https://user-images.githubusercontent.com/41024075/48375500-638ca280-e685-11e8-82bd-8d21d677aefe.gif)

**Comment by emily-phet** [comment]
my 2 cents - this seems minor to me and not worth effort to fix.

**Comment by jbphet** [comment]
Good eye @KatieWoe.

We've seen things like this before in Firefox, and it's actually an issue with the fonts in the browser.  So, given that there's not much we can do about it, and that it's minor enough that @emily-phet and @arouinfar agree that it's not worth the effort, I'm going to close this one.
