### ISSUE TITLE
Why does the focus highlight for the reset button have a stroke?

### ISSUE THREAD

**Issue by jbphet** [phetsims/resistance-in-a-wire#186]
With one exception, all all focus highlights in this sim are a simple shape with no stroke, like this one for one of the sliders:

![riaw-slider-highlight-2](https://user-images.githubusercontent.com/3082831/48160294-b389f480-e294-11e8-8cfe-30300aaa9153.png)

However, there is a stroke on the highlight when the reset button is selected, shown here:

![riaw-slider-highlight](https://user-images.githubusercontent.com/3082831/48160330-cbfa0f00-e294-11e8-82d5-86d7c4c2092c.png)

This looks a bit odd to me, and IMO would look better if it was consistent with the other highlights.  I searched through GitHub and couldn't find any issues that seemed to describe why this is like this (which isn't to say that there aren't any, I just couldn't find them).  Is there a good reason why this one focus highlight is unique?

**Comment by jessegreenberg** [comment]
When the resistance is very large it is difficult to see the pink focus highlight on top of the red letter, so a black focus highlight was added to help with visibility.

Here is the related issue: https://github.com/phetsims/resistance-in-a-wire/issues/118

Reassigning to you @jbphet.

**Comment by jbphet** [comment]
Okay.  Seems like a reasonable explanation.  Closing.
