### ISSUE TITLE
Legends Of Learning Mute Doesn't Work

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/resistance-in-a-wire#194]
For https://github.com/phetsims/QA/issues/219 when testing the functionality of the LOL harness with this sim I discovered that the mute button LOL provides (right next to start/pause/resume and end game buttons) does not mute the sound of the sim. @jbphet and I were discussing this and the possibility of adding in functionality where when the LOL mute button is hit it also activates the mute button in the sim, similar to how the pause functionality works now. Assigning to @samreid and @ariel-phet to discuss and possibly move to a more relevant repo. I have also tested with John Travoltage to make sure this is not a sim specific issue and it seems to occur with all sims that have sound.

**Comment by phet-steele** [comment]
I just wanted to point out that this isn't a "bug" or "issue" per se. It has always been the intention that we only support play/pause in LoL, and nothing else (I'm having trouble finding this in writing, but I am 100% sure this is what I've been told).

Since it has never been expected that the mute sound button should work, and since I understand that this github issue is asking about the possibility of adding this feature, I'm changing the labels of this issue to reflect that.

**Comment by samreid** [comment]
> It has always been the intention that we only support play/pause in LoL, and nothing else

That's my understanding too, but maybe we should discuss with @jbphet how much effort it would be to add this for Vibe and Tambo?

**Comment by JRomero0613** [comment]
I was also under the impression that we did not support the mute functionality, however with our work with sonification and sound cues looking to increase this might be a function that teachers appreciate if they use the legends of learning harness.

**Comment by jbphet** [comment]
@samreid said

> maybe we should discuss with @jbphet how much effort it would be to add this for Vibe and Tambo?

Supporting it in Tambo would, I think, be pretty straightforward from PhET's standpoint.  There is a sim-wide property that controls whether or not sound is enabled, and I imagine that it could be hooked up much like the current `simActiveProperty`.  So, code-wise, not hard at all.  Getting Legends of Learning to update to a newer version of the code that we provided them for their framework is another matter.  I don't know anything about how that would work, how responsive they are, and whether they would appreciate it enough to make it worth the effort.

**Comment by samreid** [comment]
> Getting Legends of Learning to update to a newer version of the code that we provided them for their framework is another matter

This would be more so that new simulations we publish from master would have this support--I don't think we would want to maintenance release existing sims for this.

**Comment by arouinfar** [comment]
I made a test playlist in LoL to see what things would look like in context. I'm not super familiar with how to use LoL, but I couldn't find a global mute button in the teacher or student views. I'm not convinced that the mute button in the LoL testing harness maps to a real control in the LoL user interface. While I think @JRomero0613 raised an excellent question, it seems like we can continue to ignore the mute button in the LoL testing harness.

Here's the teacher's view:
<img width="1440" alt="screen shot 2018-11-13 at 10 16 38 am" src="https://user-images.githubusercontent.com/8419308/48430720-3d224200-e72d-11e8-8a6a-7d732376bf98.png">

This is what the student would see. The sound on/off button in the sim behaves normally.
<img width="1440" alt="screen shot 2018-11-13 at 10 16 29 am" src="https://user-images.githubusercontent.com/8419308/48430740-4ca18b00-e72d-11e8-971c-cddfa8837ef2.png">

**Comment by samreid** [comment]
What if @arouinfar reaches out to LoL, something like:

> We noticed there is a mute control in the harness but nothing like that in the teacher or student interface.  Is there another control I missed, or another way for clients to leverage that?  Or do you have plans to add support for this in the future?

**Comment by arouinfar** [comment]
My one and only contact at LoL is not a dev, and would not be the appropriate person for this question. Let's bring it up with @kathy-phet and see if she has a more appropriate contact.

**Comment by arouinfar** [comment]
@jbphet @samreid I'm reassigning to you to decide how you'd like to move forward.

**Comment by jbphet** [comment]
Hey @samreid - I don't think I'm going to have time for this in the near future.  I also don't have any contacts at Legends of Learning.  I think we should pass on implementing this for now, and be ready to do it if and when they ask for it.

**Comment by jbphet** [comment]
And by the way @samreid, I'm okay with closing this if you are.  We can always open a more general issue about muting and LoL if we get a request to implement it.

**Comment by jbphet** [comment]
@samreid - I am fine with closing this issue, but I don't think it should be my call.  I don't know much about how the sims are used by LoL, whether this feature is likely to matter to them, and if it has been discussed with them.  It is my strongly held opinion that it isn't worth the time and effort to implement this until there is some clear direction with respect to those questions.  So sure, close it if you like and we can reopen if and when we get a request to implement, or pass it off to someone who is better positioned to make a call.  I'm fine with either.

**Comment by samreid** [comment]
Sounds good, let's escalate to @ariel-phet.

**Comment by ariel-phet** [comment]
I think until LoL makes this sort of request to us, we don't have do do anything major here. Ideally we will deal with this in Tambo, to be figured out in https://github.com/phetsims/tambo/issues/57 so in future sim releases this will not be an issue. Closing

**Comment by kathy-phet** [comment]
Added meeting: status label because I just want to know a bit more about this issue so I understand the current state for when I interact with LOL.
