### ISSUE TITLE
Internet Explorer Does not have any sound

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/resistance-in-a-wire#195]
For https://github.com/phetsims/QA/issues/219 when testing on Windows 7 on IE there is no sound at all within the sim. I checked on Windows 8 on IE to see if it occurs under these conditions as well and it does, we seem to have an issue with sound on Internet Explorer. One interesting thing about this version of the sim is that the speaker icon in the bottom corner used to mute/unmute the sim is not present in the IE versions, while the same exact URL has a sound icon and functioning sound in Chrome and Firefox on the same platform. I have attached a screenshot of this difference between browser versions of the sim.
![ie_riaw_no_sound](https://user-images.githubusercontent.com/30352536/48376085-0f82bd80-e687-11e8-87de-4d32ddc83761.JPG)

**Comment by jessegreenberg** [comment]
Can't remember for certain, but I think it was decided that we wouldn't support sound in IE11. @jbphet can you confirm?

**Comment by jbphet** [comment]
Yes, this is intentional since IE lacks support for Web Audio (Microsoft is putting all their browser development effort into Edge).  See https://github.com/phetsims/tambo/issues/6 for the history of this decision.  Closing.
