### ISSUE TITLE
Clicking out of keyboard nav moves sliders Edge

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#196]
Test device:
Dell Laptop
Operating System:
Win 10
Browser:
Edge
Problem description:
For https://github.com/phetsims/QA/issues/219#event-1953042350
When using keyboard nav on the sliders, clicking out with a mouse will cause the slider that was being controlled to jump up.
Steps to reproduce:
1. Go to the sim in edge
2. Use keyboard nav to manipulate the first slider (not exclusive to this slider)
3. Put the slider somewhere in the middle with shift arrow to make the effect easier to see
4. Use the mouse to select the mute button (or anything to stop the keyboard nav

Screenshots:
https://drive.google.com/file/d/1vA-gLGyV9gygHpTIcsKCK_pomXnW6hyE/view?usp=sharing

Troubleshooting information (do not edit):

<details>

Name: ‪Resistance in a Wire‬
URL: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.1/phet/resistance-in-a-wire_en_phet.html
Version: 1.6.0-rc.1 2018-11-07 18:26:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
Language: en-US
Window: 1920x946
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"ff00a0bb","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"fa2fbadf","branch":"HEAD"},"dot":{"sha":"bbbd8526","branch":"HEAD"},"joist":{"sha":"82521d0c","branch":"HEAD"},"kite":{"sha":"380cef53","branch":"HEAD"},"phet-core":{"sha":"1b90ac2f","branch":"HEAD"},"phet-io":{"sha":"38d7b161","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"246085c1","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"7479b0ec","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"c46f7839","branch":"HEAD"},"phet-io-wrappers":{"sha":"a6bc62ca","branch":"HEAD"},"phetcommon":{"sha":"cd63d89a","branch":"HEAD"},"query-string-machine":{"sha":"06ed6276","branch":"HEAD"},"resistance-in-a-wire":{"sha":"38ae25d0","branch":"HEAD"},"scenery":{"sha":"51716674","branch":"HEAD"},"scenery-phet":{"sha":"15dec251","branch":"HEAD"},"sherpa":{"sha":"2cd50500","branch":"HEAD"},"sun":{"sha":"5244d45e","branch":"HEAD"},"tambo":{"sha":"ad355580","branch":"HEAD"},"tandem":{"sha":"4f37a910","branch":"HEAD"}}

</details>

**Comment by KatieWoe** [comment]
Did not seem to occur in full screen.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe reassigning to me to track for next RC.

**Comment by jbphet** [comment]
Should be fixed in 1.6.0-rc.2, unassigning for now.

**Comment by KatieWoe** [comment]
This looks fixed in 1.6.0-rc.2
