### ISSUE TITLE
Chrome OS font makes rho look squished and more like p

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#197]
The font that Chrome OS (71.0.3578.27) (Lovelace) shows rho as thinner and less curved, giving it the appearance of an odd p.  Making issue per @jbphet for discussion.  For https://github.com/phetsims/QA/issues/219#event-1953042350
Chrome OS:
![x screenshot](https://user-images.githubusercontent.com/41024075/48426006-2676ed80-e723-11e8-8eab-8b5b312b5db4.png)
Chrome on Win 10 to compare:
![rho](https://user-images.githubusercontent.com/41024075/48426034-355da000-e723-11e8-8b40-37055d39708b.PNG)

**Comment by arouinfar** [comment]
@KatieWoe @jbphet I think this is just an unfortunate side effect of how browsers choose to render text. I'm not particularly sure that we can do anything about it.

That said, I still think the rho looks more like a rho than a p. Given that the other variables in the equation use a serif font, a p would look more like this:
<img src="https://user-images.githubusercontent.com/8419308/48432662-44981a00-e732-11e8-8e2a-43941faa8ddf.png" width=100>

I don't think there's anything we need to do here, so closing.
