### ISSUE TITLE
JAWS Repeats Values 

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/resistance-in-a-wire#207]
**Test Device:** Hanson
**OS:** 1803.17134.523
**Browsers:** Firefox 64.0.2, Chrome 71.0.3578.98, Edge 42.17134.1.0
**Problem Description:** When using JAWS screen reader with all browsers if any sliders are adjusted a large amount JAWS will read out a value before the last slider value multiple times, and read out the final  slider value multiple times before ending. The screen reader will not read out the normal "As rho increases letter R increases" or "The resistivity is _____" either after this bug has occurred. To replicate open JAWS and select any of the browsers above and open the sim. Use keyboard navigation to navigate to a value slider, and using the arrow keys hold down the key to move the slider for a couple of seconds (this works best when shift is held too to make the increments smaller). The slider will move a little bit but will stop moving for a couple seconds while the button is being held down, until it is released and the slider makes a large jump to the final value. The screen  reader will now read out a value between the initial and final slider  values multiple times. Sometimes the screen reader will read out a couple values multiple times for example "area is 1.52 cm squared, area is 1.52 cm squared....., area is 1.53 cm squared....". The screen reader will then read out the final value that the slider has reached multiple times and once it has concluded will not read out the normal text that is read once a slider value has been input. The time that it takes to read out these slider values can be quite long if not interrupted by making another input to the sim, taking almost 2 minutes at times.

**Comment by KatieWoe** [comment]
@jessegreenberg correct me if I'm wrong, but I believe this is known and documented in the known a11y bug tracking document number 11.

**Comment by jessegreenberg** [comment]
That is correct @KatieWoe. Thanks for making an issue @JRomero0613. But we discovered this is the behavior for ALL sliders for JAWS, even those outside of a PhET simulation. It is unfortunate, but there is nothing we can do to prevent this bug of the assistive device. Closing.
