### ISSUE TITLE
Resistor dots get messed up on Samsung Galaxy Tab 2

### ISSUE THREAD

**Issue by phetsims** [phetsims/resistance-in-a-wire#33]
The dots on the resistor disappear sometimes, sometimes only fill part of the resistor, and do other odd things on the Samsung Galaxy Tab 2.

Note: Don't fix this one yet unless it's quick and easy.  PhET and MLL will talk about whether this device can really be supported.  However, it would be good to make sure that MLL can test on this platform.

**Comment by jbphet** [comment]
The Samsung Galaxy Tab 2 is no longer a supported platform (and hasn't been for a while).  Closing.
