### ISSUE TITLE
make symbols translatable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/resistance-in-a-wire#43]
Symbols (V, R, p) are not currently localized in this sim. And they are in fact duplicated, in FormulaView and SlidersBox.

**Comment by jbphet** [comment]
Fixed with commit aed7422534251ffbd0498a6efda8640122dd43f5, but referenced the commit to the closely related issue #59.

**Comment by elisemorgan** [comment]
Fixed 
Related to https://github.com/phetsims/tasks/issues/531
