### ISSUE TITLE
Publish teacher tips when HTML5 version is "main" version of Resistance in a Wire (include bit about what the dot representation means)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/resistance-in-a-wire#46]
Also make sure to answer phethelp user question:

I have a question regarding resistance of wire - in your applet on resistivity increasing resistivity is shown by adding grey dots in the wire.  I think this is confusing as the number of atoms is not changing, it is the nuumber of conduction electrons which is decreasing.  Particularly at A level where we consider conductivity, your applet has the ability to be confusing, which is the opposit of what we want (and invariably get) from a Phet applet.  I do not know how to represent opposition to current btw - so perhaps it should be a conductivity applet instead??  It could then look at semiconductors and 'insulators' too??

**Comment by ariel-phet** [comment]
Looks like this sim needs an updated teacher tips, and this was probably supposed to happen with the whole switch over to the HTML5 sim pages. Not a major rush since not a super popular sim, but would be good to take care of.

**Comment by ariel-phet** [comment]
Btw @arouinfar, @phet-steele has now helped with a few teacher tips. His plate is fairly full with QA tasks currently, but he could help on this task when those settle down and help set up a nice skeleton for the teacher tips (with screenshots and such)

**Comment by arouinfar** [comment]
Sounds good @ariel-phet. I will coordinate with @phet-steele to get these tips done once his QA workload settles down.

**Comment by ariel-phet** [comment]
@arouinfar, I don't think @phet-steele's QA load is going to settle any time soon, please take on this task yourself

related to https://github.com/phetsims/tasks/issues/524

**Comment by arouinfar** [comment]
Got it @ariel-phet. I will prioritize this issue on Friday.

**Comment by arouinfar** [comment]
Teacher tips have been uploaded. Closing.
