### ISSUE TITLE
some references to resistance-in-a-wire/js/view/shape-views/slider-box-view/slider.js are miscapitalized

### ISSUE THREAD

**Issue by olleicua** [phetsims/resistance-in-a-wire#47]
references are made to `Slider.js` that break the sim on case sensitive file systems.

**Comment by ariel-phet** [comment]
@jbphet might be good to verify if this can be closed.

**Comment by jbphet** [comment]
I searched through the code and it looks like @samreid fixed all occurrences.  Closing.
