### ISSUE TITLE
reduce coupling to ResistanceInAWireModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/resistance-in-a-wire#58]
There are many cases where a constructor has parameter:

`@param {ResistanceInAWireModel} model`

... but only needs access to one or two things in the model. 

For example:

`function CurrentResistanceView( model, x, y, w )`

... only needs access to `model.resistanceProperty`, so a better constructor would be:

`function CurrentResistanceView( resistanceProperty, x, y, w )`

**Comment by veillette** [comment]
After the refactoring, the model for resistance in a wire does contain only four properties.

 Four of the view modules need all the properties from the model and one needs  three of these properties which is more or less the entire model.

Therefore, it makes sense to pass the entire model.
  
Closing.
