### ISSUE TITLE
name mismatch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/resistance-in-a-wire#61]
Filename `ResistanceInAWireStageContainer.js` contains type `ResistanceInAWireStage`.

**Comment by pixelzoom** [comment]
Btw... I would move all of the code in the `ResistanceInAWireStage` constructor into `ResistanceInAWireView`.  It adds nothing to have this addition type.

**Comment by jbphet** [comment]
I have gotten rid of the "Stage" classes and structured the code to more closely match our current conventions, see #67.  Closing.
