### ISSUE TITLE
reset anti-pattern

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/resistance-in-a-wire#62]
ResistanceInAWireModel extends PropertySet, and has 4 Properties:

```js
    PropertySet.call( this, {
      resistance: 0,
      resistivity: 0.5,
      length: 10,
      area: 7.5
    } );
```

It overrides reset like this:

```js
    reset: function() {
      this.resistivityProperty.reset();
      this.lengthProperty.reset();
      this.areaProperty.reset();
    }
```

There is a bug here, typical of this anti-pattern; the `resistance` Property is not being reset in this override. 

And this override is likely unnecessary, since PropertySet handles resetting all of its Properties.

**Comment by pixelzoom** [comment]
Whoa... There's another discrepancy here: `resistance` versus `resistivityProperty`. The latter is used throughout client code, and I don't see it defined anywhere, so I'm not sure how this sim is even working.

**Comment by jbphet** [comment]
Fixed, closing.
