### ISSUE TITLE
showPointerAreas not showing on sliders

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/resistance-in-a-wire#64]
Related to https://github.com/phetsims/tasks/issues/479

Test device: Personal Mac

Operating System: OS X 10.10.5

Browser: Chrome 47.0.2526.106

Problem description: In Ohm's Law, the sliders are highlighted with showPointerAreas, but in Resistance in a Wire they are not. I'm not sure whether or not this is an issue, but it is an inconsistency.

Steps to reproduce: showPointerAreas test

Severity:

Screenshots:
showPointerAreas:
![screen shot 2016-01-15 at 1 26 28 pm](https://cloud.githubusercontent.com/assets/12610678/12364411/a164ebf8-bb8b-11e5-83bb-1a78995e280b.jpg)

Troubleshooting information (do not edit):
Name: ‪Resistance in a Wire‬
URL: http://phettest.colorado.edu/resistance-in-a-wire/resistance-in-a-wire_en.html?ea&brand=phet&showPointerAreas
Version: 1.2.0-dev.1 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Language: en-US
Window: 1268x653
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by jbphet** [comment]
I looked briefly at this, and it appears to be an issue with how the knobs are created in Slider.js.  It could be fixed, but doesn't seem worth the effort, since I checked with @phet-steele and he said that there were no issues with using the knobs on touch devices.  I'm going to label this as "won't fix" and close it.
