### ISSUE TITLE
Layout tweaks

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/resistance-in-a-wire#65]
Since this was one of our earliest HTML5 sims, we had not decided on some general look standards. Would be good to change the layout a bit to that shown below:

![riaw](https://cloud.githubusercontent.com/assets/4051174/13094667/6f8b5142-d4c9-11e5-9bd3-7ab2c2808503.PNG)

**Comment by ariel-phet** [comment]
@jbphet if this is truly an easy change, go ahead and do it for the redeploy when addressing i18n issues, if not, please just mark as deferred and an unassign yourself

**Comment by jbphet** [comment]
assigning to @ariel-phet to verify on v1.2.0-rc.1 (http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.0-rc.1/resistance-in-a-wire_en.html)

**Comment by ariel-phet** [comment]
@jbphet now that you moved the symbols to all be on the same "baseline" the resistance readout needs a bit more negative space. I think we should extend the panel vertically a smidge and add negative space as shown in the mockup below:

![riaw](https://cloud.githubusercontent.com/assets/4051174/13367719/d274c8f8-dca1-11e5-8cfc-da40e8c854d8.PNG)

**Comment by ariel-phet** [comment]
otherwise, all changes look good!

**Comment by jbphet** [comment]
Assigning to @ariel-phet to verify latest round of 'tweaks' on v1.2.0-rc.2 (http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.0-rc.2/resistance-in-a-wire_en.html).

**Comment by ariel-phet** [comment]
looks good, closing
