### ISSUE TITLE
clipping not working on Edge 20

### ISSUE THREAD

**Issue by jbphet** [phetsims/resistance-in-a-wire#68]
Clipping is now used for the dots shown in the wire.  This works great in most places, but is not working on Edge 20.  If I start the sim and immediately reduce the length of the wire, it looks like the screen shot below.  As soon as the window is resized, the clipping kicks in and the dots look good.

![riaw-clip-issue](https://cloud.githubusercontent.com/assets/3082831/13295472/463ce6c0-dae6-11e5-842e-a1b8ffebd563.PNG)

**Comment by jbphet** [comment]
Discussed with @jonathanolson and he has logged a Scenery issue, see https://github.com/phetsims/scenery/issues/521.

**Comment by phet-steele** [comment]
@jbphet resolved in 1.2.0-rc.2
