### ISSUE TITLE
text artifact on Edge

### ISSUE THREAD

**Issue by jbphet** [phetsims/resistance-in-a-wire#69]
On Edge version 20.10240.16384.0 the following odd artifact is seen:

![riaw-text-artifict](https://cloud.githubusercontent.com/assets/3082831/13295567/bac74580-dae6-11e5-8dce-a2ead264e9c8.PNG)

**Comment by jbphet** [comment]
This was also seen in Graphing Lines, see https://github.com/phetsims/graphing-lines/issues/60.

**Comment by jbphet** [comment]
I discussed this with @jonathanolson and he has logged a Scenery issue, see https://github.com/phetsims/scenery/issues/520.

**Comment by phet-steele** [comment]
@jbphet resolved in 1.2.0-rc.2
