### ISSUE TITLE
Area and radius of the wire

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/resistance-in-a-wire#70]
It's bugging me that the displayed area is not at all proportional to the area slider.

The area slider controls the radius of the wire (not area), so the displayed area is the square of what is shown in the slider. This makes it off by a factor of 5 or so.

Should this be ignored?

**Comment by ariel-phet** [comment]
It should be ignored for now, at some point we will go back and do a thorough code review of RIAW (likely when ready for instrumenting) and we can address then. Marking as priority deferred and clearing assignee

**Comment by ariel-phet** [comment]
@zepumph @phet-steele pointed out that this should probably be taken care of (note the old comment above). You and I can work on polishing it, but basically I would keep the maximum "visual size" the same and we can do a proper scaling so the radius shrinks down properly (but nowhere near as small as now)

**Comment by zepumph** [comment]
Ignore the commit and revert from phet-io-wrappers above, oops. I made it so that the diameter of the wire is accurate to the formula. @ariel-phet please pull master and see how you like it.

**Comment by ariel-phet** [comment]
Pulled and looks good! Closing

**Comment by ariel-phet** [comment]
thanks @zepumph
