### ISSUE TITLE
Rtl causes no symbols to be in equation, and causes IE11 to crash

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/resistance-in-a-wire#71]
When using stringTest=rtl, there are no symbols whatsoever in the equation.
![capture](https://cloud.githubusercontent.com/assets/11947677/13367453/0f11693a-dca0-11e5-80b2-1945bad745eb.PNG)

I'm not sure if this was intended related to #43 or not, but it looks like a problem.
Tested on Windows 7, all browsers.

**Comment by brroberts1231** [comment]
Test device: Personal Windows 7

Operating System: Windows 7 64-bit


Browser: IE11

Problem description: With stringTest=rtl, attempting to drag any slider in IE11 will cause the browser to crash. 

Steps to reproduce: Use stringTest=rtl, drag any slider, IE will become unresponsive. 

Troubleshooting information (do not edit):
  
Name: ‫تست (زبان)‬

URL: http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.0-rc.1/resistance-in-a-wire_en.html?stringTest=rtl

Version: 1.2.0-rc.1 2016-02-26 20:30:27 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; CMNTDFJS; .NET4.0E; .NET4.0C; GWX:DOWNLOADED; rv:11.0) like Gecko

Language: en-US

Window: 1366x673

Pixel Ratio: 1/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"6404a0f9","branch":"HEAD"},"babel":{"sha":"a0fffdf4","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"40bb0057","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"9891b43b","branch":"HEAD"},"resistance-in-a-wire":{"sha":"04826a5a","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"ccc2b3bd","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

**Comment by brroberts1231** [comment]
Related to phetsims/tasks#528

**Comment by jbphet** [comment]
Looks like the code needs to be a bit more thorough in extracting printable characters from a string that included direction embedding symbols.  I've added this, and it fixes it on Chrome.  Will test on IE11.

**Comment by jbphet** [comment]
Just tested this fix on IE11 with @phet-steele, and it did not crash.

**Comment by phet-steele** [comment]
@jbphet resolved in 1.2.0-rc.2
