### ISSUE TITLE
stringTest=xss fails

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/resistance-in-a-wire#72]
Test device: Dirac

Operating System: OSX 10.11.3

Browser: Safari, Firefox, Chrome

Problem description: When using stringTest=xss, the loading icon briefly appears, but then the page just goes black without loading the sim.

Screenshots:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11947677/13470537/d8cd1694-e069-11e5-8a8e-faf4672e3b27.gif)

Troubleshooting information (do not edit):
Name: ‪Resistance in a Wire‬
URL: http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.0-rc.2/resistance-in-a-wire_en.html
Version: 1.2.0-rc.2 2016-02-29 19:18:02 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
Language: en-US
Window: 1115x626
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"6404a0f9","branch":"HEAD"},"babel":{"sha":"c9582b88","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"40bb0057","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"9891b43b","branch":"HEAD"},"resistance-in-a-wire":{"sha":"e92a51e9","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"ccc2b3bd","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

Related to phetsims/tasks#531

**Comment by jbphet** [comment]
This is a problem with SubSupText and/or the nature of the xss string test, and does not reflect any sort of vulnerability or bug in the sim.  I've logged a ticket in scenery-phet to fix the problem long term, see https://github.com/phetsims/scenery/issues/528, and will close this issue here.
