### ISSUE TITLE
1.2.0-rc.2 wire gradient

### ISSUE THREAD

**Issue by phet-steele** [phetsims/resistance-in-a-wire#73]
The gradient in the wire is vastly different in this new version when compared to an older version:
New:
![resistanceinawiregradientnew](https://cloud.githubusercontent.com/assets/5863899/13509419/8f157ed0-e148-11e5-8e63-5b936aabfaf6.PNG)

Old (1.1.0)
![resistanceinawiregradientold](https://cloud.githubusercontent.com/assets/5863899/13509435/a26a550a-e148-11e5-8c44-58f3397c6d76.PNG)

@jbphet says this was not an intentional change and will be reverted. Two additional notes: Edge shows a different gradient (the dark part along the bottom is not there) and the gradient does not get redrawn when the wire's shape is updated. For phetsims/tasks/issues/531. These gradients were viewed on all Win 10 browsers.

Troubleshooting information:
Name: ‪Resistance in a Wire‬
URL: http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.0-rc.2/resistance-in-a-wire_en.html
Version: 1.2.0-rc.2 2016-02-29 19:18:02 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36
Language: en-US
Window: 1600x775
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"6404a0f9","branch":"HEAD"},"babel":{"sha":"c9582b88","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"40bb0057","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"9891b43b","branch":"HEAD"},"resistance-in-a-wire":{"sha":"e92a51e9","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"ccc2b3bd","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

**Comment by jbphet** [comment]
Good eye.  I started working to fix this, and thought, "While we're messing with this, why not make the wire look like copper, since that's the material that most people associate with wires?"  I discussed with @ariel-phet and Mike D and both were fine with it, so I'm going for it.

**Comment by jbphet** [comment]
I've made the wire look more like copper, here's a cropped screen shot:

![riaw-copper-wire](https://cloud.githubusercontent.com/assets/3082831/13538432/bbc47598-e207-11e5-8ac9-84cb704ec01f.PNG)

**Comment by phet-steele** [comment]
@jbphet the gradient has certainly been adjusted and updates correctly when changing area (on may platforms & 1.2.0-rc.3).
