### ISSUE TITLE
ResistanceInAWireModel is not created on demand

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/resistance-in-a-wire#76]
`ResistanceInAWireScreen` constructor looks like this:

```js
  function ResistanceInAWireScreen() {
    var model = new ResistanceInAWireModel();
    Screen.call( this,
      function() { return model; },
      function( model ) { return new ResistanceInAWireScreenView( model ); },
      { backgroundColor: '#ffffdf' }
    );
  }
```

The model is not supposed to be instantiated by the constructor, it's supposed to be instantiated on demand by Sim.js, when the Screen's `createModel` function is called.  Unless there's a good reason to do things differently in this sim, the constructor should look like this:

```js
  function ResistanceInAWireScreen() {
    Screen.call( this,
      function() { return new ResistanceInAWireModel(); },
      function( model ) { return new ResistanceInAWireScreenView( model ); },
      { backgroundColor: '#ffffdf' }
    );
  }
```

If there is a legitimate reason why it needs to be different, please document it.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/bending-light/issues/356#issuecomment-245826609, @samreid said:
> Those problems will interfere with the loading bar (if nothing else), we should address them.

**Comment by samreid** [comment]
I realized this will not interfere with the current loading bar proposal, but it should still be fixed.

**Comment by jbphet** [comment]
fixed, closing
