### ISSUE TITLE
Instrument for PhET-iO

### ISSUE THREAD

**Issue by samreid** [phetsims/resistance-in-a-wire#77]
This is a small and simple simulation and would be a great introduction to sim instrumentation for @zepumph.  Would be good to collaborate on to start with.  Generally, we'll paste the checklist from https://github.com/phetsims/phet-io/blob/36d9b4cb5e01107bd5fab43b0fb1a54b14d73e69/doc/how-to-instrument-a-phet-simulation-for-phet-io.md into this comment and follow those directions.

# How to Instrument a PhET Simulation for PhET-iO

## Overview of instrumentation steps:
 - [x] Copy this checklist to the issue description (top issue comment) for tracking. Make sure to use a permanent link like `/blob/<SHA>/` so that the specific guide you used is preserved.
 - [x] [Understand the goal](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#understand-the-goal)
 - [x] [Code review](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#code-review)
 - [x] Use Property instead of PropertySet
 - [x] [Import Tandem to main.js](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#import-tandem-to-mainjs)
 - [x] [Create root tandem](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#create-root-tandem)
 - [x] [Pass tandems to sim screens](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-sim-screens)
 - [x] [Pass tandems to model and view](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-model-and-view)
 - [x] [Pass tandems to all constructors defined by the simulation](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-all-constructors-defined-by-the-simulation)
   + See also [Testing while adding Tandem instances](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#testing-while-adding-tandem-instances). Test with `?phetioValidateTandems=false` since some common code-components don't yet have tandems.
 - [x] [Pass tandem instances to common code components](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandem-instances-to-common-code-components)
   + See also [Testing while adding Tandem instances](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#testing-while-adding-tandem-instances).
 - [x] [Replace types with tandemized equivalents](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#replace-types-with-tandemized-equivalents)
 - [x] [Instrument any uninstrumented common-code components used by the sim](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#instrument-any-uninstrumented-common-code-components-used-by-the-sim)
 - [x] [Instrument new component types defined by the sim](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#instrument-new-component-types-defined-by-the-sim)
 - [x] [Add simulation specific support](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#add-simulation-specific-support)
 - [x] [Support dynamic state](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#support-dynamic-state)
 - [x] Make sure Joist `dt` values are used instead of Date.now() or other Date functions.  This is necessary for reproducible playback via input events.
 - [x] Are random numbers using `phet.joist.random`, and all doing so after modules are declared (non-statically)?  For instance, the following methods (and perhaps others) should not be used: `Math.random`, `_.shuffle`, `_.sample`, `_.random`
 - [x] `undefined` values cannot be saved by phet-io, sims should be written to use `null` instead
 - [x] Verify that the simulation works in all of the phet-io wrappers
 - [x] Build with `grunt --brand=phet-io` and test the built version by launching build/wrappers/index and testing all the links
 - [ ] Set up a task to have the newly instrumented sim tested by the QA team
 - [ ] Update these instructions if you find them to be incomplete, inconsistent or incorrect
 - [ ] After publishing, add your instrumented simulation to the spreadsheet here: https://docs.google.com/spreadsheets/d/1pU9izdNQkd9vr8TvLAfXe_v68yh-7potH-y712FBPr8/edit#gid=0

**Comment by zepumph** [comment]
I have done many steps in the check list. I need to make sure that @samreid and I work on https://github.com/phetsims/phet-io/issues/1080 in this issue.

**Comment by samreid** [comment]
I emailed the skype channel:

> MK & I are preparing Resistance in a Wire for phet & phet-io rc testing.  We are trying to decide if we should use the the legacy process (as was used for molarity) which has separate branches and dependencies.json for each brand, or if we should test the waters with using just one branch and one dependencies.json.

**Comment by samreid** [comment]
@jonathanolson recommended using the legacy process for Resistance in a Wire until we have had more time to consider finalize the "one branch" process.

**Comment by zepumph** [comment]
The rc phet-io version has been deployed and has been sent into the test queue. Closing.
