### ISSUE TITLE
How to handle ._shuffle

### ISSUE THREAD

**Issue by veillette** [phetsims/resistance-in-a-wire#83]
For PhET-IO, how should,
```
    // randomize the array of dots so that we can show/hide them in a random way as resistivity changes
    dotGroup.children = _.shuffle( dotGroup.children );
```
in WireNode.js be handled, if at all?

**Comment by jbphet** [comment]
Hi @veillette!  If you're asking about how to make it compatible with phet-io so that results are repeatable, plese use `phet.joist.random.shuffle`.

**Comment by zepumph** [comment]
I fixed the line of code. Closing
