### ISSUE TITLE
Make phet and phet-io branches and publish rcs for testing. 

### ISSUE THREAD

**Issue by zepumph** [phetsims/resistance-in-a-wire#86]

**Comment by zepumph** [comment]
http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-rc.1/

**Comment by zepumph** [comment]
http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiorc.1/

**Comment by zepumph** [comment]
Both are published, take a look at https://github.com/phetsims/tasks/issues/836. Closing

**Comment by phet-steele** [comment]
Above commit is for #89..... 😢
