### ISSUE TITLE
Release new version for phet and phet-io brand

### ISSUE THREAD

**Issue by zepumph** [phetsims/resistance-in-a-wire#88]
from https://github.com/phetsims/QA/issues/4#event-1139529251, it would be good to do a dev release first. I will do one for phet-io, and then create RC's for the phet and phet-io versions.

I should do these first:
* https://github.com/phetsims/sun/issues/289#issuecomment-300243201 (use the default thumb with silver)
* https://github.com/phetsims/sun/issues/293 for RIAW before this though.

**Comment by zepumph** [comment]
After talking with @ariel-phet, we think the best approach to get both a phet-io and phet brand published is to do the following three qa tests:

1. phet brand dev release
2. phet brand rc
3. phet-io rc

**Comment by zepumph** [comment]
Alright the dev version is ready

**Comment by zepumph** [comment]
https://github.com/phetsims/QA/issues/16

**Comment by zepumph** [comment]
Make sure to do https://github.com/phetsims/resistance-in-a-wire/issues/89 before publishing

**Comment by zepumph** [comment]
Issues to tackle before RC:

https://github.com/phetsims/resistance-in-a-wire/issues/28
https://github.com/phetsims/resistance-in-a-wire/issues/91

**Comment by zepumph** [comment]
I made some substantial changes in #91, and I will do another dev test before going to RC.

**Comment by zepumph** [comment]
phet-io dev test: https://github.com/phetsims/QA/issues/32

**Comment by phet-steele** [comment]
@zepumph don't forget #96 either!

**Comment by jessegreenberg** [comment]
@zepumph what is the status of this issue?  We are ready to deploy a PhET brand RC of this sim with keyboard navigation, should we coordinate?

**Comment by zepumph** [comment]
I think there is just https://github.com/phetsims/ohms-law/issues/68 (which effects RIAW as well). I would love some help on it, I think it has to do with some layout changes I did earlier in the summer, but I can't track down the problem.

**Comment by jessegreenberg** [comment]
Ok, thanks @zepumph.  Does that need to be fixed before a redeploy?  Does the currently deployed version have that issue as well?

**Comment by zepumph** [comment]
I don't think it is in the latest version on phet. I'll take another look at it and see what I can do.

**Comment by zepumph** [comment]
https://github.com/phetsims/ohms-law/issues/68 is fixed, and we are ready for a release. I'm not sure if we should do a PhET-iO version now, since there seems to be no request for it. @samreid do you think we should release RIAW for phet-io right now?

**Comment by samreid** [comment]
It is up to @kathy-phet.

**Comment by samreid** [comment]
On second thought, If the sim is improved, it seems we should also test and publish the phet-io one too.

**Comment by zepumph** [comment]
@samreid how stable do you think master is right now due to https://github.com/phetsims/phet-io/issues/1223. Should we worry?

**Comment by samreid** [comment]
It still needs attention and should be considered unstable.  You could grab an estimate earlier sha or wait unit it is resolved

**Comment by zepumph** [comment]
I think that resolution sounds like a good idea. I will crank away at some of them, and try to get it more stable so we can figure out if that's the way we want to go definitively.

**Comment by zepumph** [comment]
@jessegreenberg think that master is more stable now for an RC

**Comment by jessegreenberg** [comment]
Thanks @zepumph!

**Comment by jessegreenberg** [comment]
A phetio rc was deployed for testing here:
https://github.com/phetsims/QA/issues/53

Once it passes testing, phet branded version will use the same SHAs.

**Comment by zepumph** [comment]
Unassigning, let me know how I can help.

**Comment by jessegreenberg** [comment]
@zepumph in #107 we decided not to include keyboard nav in phet-io releases until a11y features work with PhET-iO.  So the current plan is  to deploy 1.3-phetio without keyboard nav and then a 1.4 PhET brand version with keyboard nav.  Does that sound correct?

**Comment by zepumph** [comment]
That sounds like our current plan, although it is kinda a pain in the butt. I want to double check with @samreid. Sam does this seem right to you?

**Comment by samreid** [comment]
Perhaps we should defer further phet-io releases until we get Faraday's Law stabilized and have PhET-iO design meetings for each sim?

**Comment by zepumph** [comment]
That would be a question for @kathy-phet, using the old way of instrumenting. OL and RIAW are both ready for phet-io releases. The question is should we spend the QA time to do this if we will just need to republish a "stable" version soon.

**Comment by zepumph** [comment]
@kathy-phet should we proceed with RIAW phet-io release even though it has not had design time to move it to a "stable api?"

**Comment by zepumph** [comment]
phetio 1.3.0-phetio released!
https://phet-io.colorado.edu/sims/resistance-in-a-wire/1.3.0-phetio/wrappers/index/

**Comment by zepumph** [comment]
@jessegreenberg you are taking on the phet version in a different issue and a different version (since it has accessibility enabled by default). Closing.
