### ISSUE TITLE
QA Credits

### ISSUE THREAD

**Issue by phet-steele** [phetsims/resistance-in-a-wire#89]
This sim is void of QA credits.....let's add them!

`Steele Dalton, Bryce Griebenow, Elise Morgan, Oliver Orejola, Benjamin Roberts, Bryan Yoelin`

@zepumph, please do not close until 1.3 is published, but feel free to add these now. 

For phetsims/QA/issues/16.

**Comment by zepumph** [comment]
@phet-steele let me know if this looks good to you.

**Comment by phet-steele** [comment]
@zepumph it's good, but we need more now. `Alex Dornan, Ethan Johnson`as well, please. You'll probably have to put a line break in there somewhere.

**Comment by zepumph** [comment]
Thanks @phet-steele, closing

**Comment by phet-steele** [comment]
You didn't preserve the alphabetic sorting 😛 . Fixed it myself but totally referenced the commit to the issue above because that's how I roll.

**Comment by zepumph** [comment]
Oops sorry, this commit here fe7aafe

**Comment by zepumph** [comment]
because of https://github.com/phetsims/joist/issues/435, we don't need the newline anymore. Should be good now!
