### ISSUE TITLE
Keyboard navigation Home/End on AreaSlider causes the sim to freeze in Firefox

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/resistance-in-a-wire#90]

**Comment by jessegreenberg** [comment]
Sometimes, not always.

**Comment by phet-steele** [comment]
@jessegreenberg what does Home/End do? In your tests, were you making the R very large with keyboard nav? A big R on Mac FF is no bueno for performance, sort of documented at https://github.com/phetsims/resistance-in-a-wire/issues/28#issuecomment-313237439

**Comment by jessegreenberg** [comment]
Yes, 'End' will make R the biggest value it can be.  I just reproduced this by sliding with the mouse, so this does not seem related to keyboard nav.

It looks like the sim is effectively frozen when R is big in FF.

**Comment by jessegreenberg** [comment]
Closing, this is surely caused by #28.
