### ISSUE TITLE
[i18n] Equation shifts and panel enlarges

### ISSUE THREAD

**Issue by phet-steele** [phetsims/resistance-in-a-wire#91]
Here is `?stringTest=double` in 1.3.0-dev.2:

<img width="1920" alt="screen shot 2017-07-11 at 11 01 42 am" src="https://user-images.githubusercontent.com/5863899/28080287-acdd2db2-6628-11e7-8c18-cfe95fb7ba54.png">

Point of comparison in production version (the good behavior!):
<img width="1920" alt="screen shot 2017-07-11 at 11 01 28 am" src="https://user-images.githubusercontent.com/5863899/28080408-248fef84-6629-11e7-88a4-27c8b71bc55d.png">

Seen on macOS 10.12.5 Chrome. For phetsims/QA/issues/16.

URL: http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-dev.2/resistance-in-a-wire_en.html?stringTest=double
Version: 1.3.0-dev.2 2017-07-06 02:32:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Language: en-US
Window: 1920x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"fd28f6a0","branch":"master"},"babel":{"sha":"2c4e2a1c","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"935747d9","branch":"master"},"dot":{"sha":"3d9d2f3d","branch":"master"},"joist":{"sha":"aad930be","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"phet-core":{"sha":"76ec0204","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"resistance-in-a-wire":{"sha":"f3ac8607","branch":"master"},"scenery":{"sha":"ff212c09","branch":"master"},"scenery-phet":{"sha":"f95f098f","branch":"master"},"sherpa":{"sha":"b0dd5fe8","branch":"master"},"sun":{"sha":"483afe13","branch":"master"},"tandem":{"sha":"f3949f64","branch":"master"}}

**Comment by zepumph** [comment]
@phet-steele would you look at http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-dev.5/resistance-in-a-wire_en.html?stringTest=double and see if the layout seems better to you now. I see that the numerator variables still overlap, but I seem to remember @samreid telling me that this is expected from the current implementations of OL and RIAW, and ok.

**Comment by phet-steele** [comment]
@zepumph this is fine. Not perfect when compared to published, but `?stringTest=double` passes without totally changing the layout like before.
