### ISSUE TITLE
Mockup of Keyboard Nav Dialog

### ISSUE THREAD

**Issue by emily-phet** [phetsims/resistance-in-a-wire#92]
Need customized keyboard nav help dialog. Should include two sections (note: wording not refined) with content for:

- Sliders
Arrow keys move slider
Shift + arrow keys, Smaller step size modifier (Resistance)
FN + arrow keys, Larger step size modifier
PG Up/Pg Dn Jumps to slider min/max

- General [this is same as in other sims]	
Tab key forward
Shift-Tab backward
Esc closes dialog

Should follow same design as latest BASE dialog, regarding capitalization, bold font, etc.

**Comment by arouinfar** [comment]
@emily-phet I imagine this dialog will be (nearly) identical to the one in https://github.com/phetsims/ohms-law/issues/61. I pasted a few options into that issue, so temporarily unassigning myself.

**Comment by jessegreenberg** [comment]
This can be closed, we added one in #101 that looks the same as the one @arouinfar mocked up in https://github.com/phetsims/ohms-law/issues/61.  A "long term" style for the Dialog is still getting designed, but this will get us through publication of this sim with keyboard nav. Closing.
