### ISSUE TITLE
Pixel polishes

### ISSUE THREAD

**Issue by zepumph** [phetsims/resistance-in-a-wire#95]
RIAW has gone through a lot in the last few months. Especially in #28. This issue is to fine tune it before dev testing.

From https://github.com/phetsims/resistance-in-a-wire/issues/28#issuecomment-319457938, @ariel-phet thought there should be two changes:
- [x] "rho" is a lower case letter, it should be aligned with the 'L' accordingly, like in the published version
- [x] The 'R' scaling is very minimal when resistance is low (less than 2). It should change more realistic to its value. (when the value doubles, the 'R' should be noticeably differently sized as well)

**Comment by zepumph** [comment]
Here is the next version @ariel-phet to look at. The scaling is basically what it was before, but now it works on firefox. The key for #28 was to make the text size small, and the scale it large, rather than having a large text that scales down and up (just an fyi).

Would you look at this link on firefox to make sure that it isn't laggy for you either. Also I want you to comment on a difference from the published version. The equal's sign and dividing line are on top of the letters. I think this is nice, and less disorienting when the R takes up the whole screen, but notice how the 'rho' tail goes underneath the dividing line. Let me know what you think, and if there is anything else.

http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-dev.8/resistance-in-a-wire_en.html

**Comment by ariel-phet** [comment]
@zepumph looks great, I think the layering of the dividing line and equals sign is a nice touch/improvement!

**Comment by zepumph** [comment]
Thanks for all your help!
