### ISSUE TITLE
Screenshot needs updating

### ISSUE THREAD

**Issue by phet-steele** [phetsims/resistance-in-a-wire#96]
@zepumph, please before #88.

**Comment by zepumph** [comment]
@phet-steele I think this is is top again, @jessegreenberg and I are rolling out new phet and phet-io versions quite soon.

**Comment by phet-steele** [comment]
> Update: I never remember, is this a step that should be done before branching?

Nope! This step isn't done until the sim passes all testing.

**Comment by phet-steele** [comment]
@jessegreenberg, screenshots are updated.

**Comment by jessegreenberg** [comment]
Great, thanks @phet-steele!
