### ISSUE TITLE
No max width on the slider value text

### ISSUE THREAD

**Issue by phet-steele** [phetsims/resistance-in-a-wire#97]
@zepumph I'm not entirely convinced that this is important to address.

Editing these three tandems...

```
resistanceInAWire.resistanceInAWireScreen.resistanceInAWireScreenView.controlPanel.resistivitySlider.valueText
resistanceInAWire.resistanceInAWireScreen.resistanceInAWireScreenView.controlPanel.lengthSlider.valueText
resistanceInAWire.resistanceInAWireScreen.resistanceInAWireScreenView.controlPanel.areaSlider.valueText
```
...and making the text long enough pushes sliders out of the panel. It seems there is no max width where there should be.

<img width="768" alt="screen shot 2017-08-07 at 10 30 05 am" src="https://user-images.githubusercontent.com/5863899/29036139-70208a98-7b5b-11e7-862c-69f105e15951.png">

Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/32.

**Comment by zepumph** [comment]
Thanks @phet-steele. Good catch.

**Comment by phet-steele** [comment]
@zepumph, still some slight movement, but the movement stops after the text reaches a certain length. Probably just the the maxWidth is **slightly** too large. Not too concerned for the initial dev release.

**Comment by zepumph** [comment]
This is fixed now, I wasn't setting the maxWidth of the SliderUnits correctly. Closing
